import { writeFileSync, accessSync } from "fs";
import { ALU, Addr, Cond, Data, IUinst, Op2, PC, RSrc, build, dot, v3HexWordsPlain } from "./mimo";

import { Instr } from "./isa"

const BRI_END = 145;

const UCODE: Record<number, IUinst> = {
    // instruction fetch
    0: { addrsel: Addr.PC, irload: 1 },
    1: { pcload: 1, idxsel: 1 },

    [Instr.mov]: { dwrite: 1, regsrc: RSrc.SRC_REG, next: 0 },

    [Instr.li]: { dwrite: 1, regsrc: RSrc.DATA_BUS, pcload: 1, next: 0 },

    [Instr.add]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.ADD,
        op2sel: Op2.T_REG,
        next: 0,
    },
    [Instr.sub]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.SUB,
        op2sel: Op2.T_REG,
        next: 0,
    },
    [Instr.mul]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.MUL,
        op2sel: Op2.T_REG,
        next: 0,
    },
    [Instr.div]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.DIV,
        op2sel: Op2.T_REG,
        next: 0,
    },
    [Instr.mod]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.MOD,
        op2sel: Op2.T_REG,
        next: 0,
    },
    [Instr.and]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.AND,
        op2sel: Op2.T_REG,
        next: 0,
    },
    [Instr.orr]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.OR,
        op2sel: Op2.T_REG,
        next: 0,
    },
    [Instr.xor]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.XOR,
        op2sel: Op2.T_REG,
        next: 0,
    },
    [Instr.nnd]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.NAND,
        op2sel: Op2.T_REG,
        next: 0,
    },
    [Instr.nor]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.NOR,
        op2sel: Op2.T_REG,
        next: 0,
    },
    [Instr.not]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.NOT,
        op2sel: Op2.T_REG,
        next: 0,
    },
    [Instr.lsl]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.LSL,
        op2sel: Op2.T_REG,
        next: 0,
    },
    [Instr.lsr]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.LSR,
        op2sel: Op2.T_REG,
        next: 0,
    },
    [Instr.asr]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.ASR,
        op2sel: Op2.T_REG,
        next: 0,
    },
    [Instr.rol]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.ROL,
        op2sel: Op2.T_REG,
        next: 0,
    },
    [Instr.ror]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.ROR,
        op2sel: Op2.T_REG,
        next: 0,
    },

    // ALU ops with 2 Registers and an immediate (1st op is load imm + increment PC, second OP is the actual ALU op)
    [Instr.addi]: { imload: 1, pcload: 1, next: 128 },
    [Instr.subi]: { imload: 1, pcload: 1, next: 129 },
    [Instr.muli]: { imload: 1, pcload: 1, next: 130 },
    [Instr.divi]: { imload: 1, pcload: 1, next: 131 },
    [Instr.modi]: { imload: 1, pcload: 1, next: 132 },
    [Instr.andi]: { imload: 1, pcload: 1, next: 133 },
    [Instr.orri]: { imload: 1, pcload: 1, next: 134 },
    [Instr.xori]: { imload: 1, pcload: 1, next: 135 },
    [Instr.nndi]: { imload: 1, pcload: 1, next: 136 },
    [Instr.nori]: { imload: 1, pcload: 1, next: 137 },
    [Instr.noti]: { imload: 1, pcload: 1, next: 138 },
    [Instr.lsli]: { imload: 1, pcload: 1, next: 139 },
    [Instr.lsri]: { imload: 1, pcload: 1, next: 140 },
    [Instr.asri]: { imload: 1, pcload: 1, next: 141 },
    [Instr.roli]: { imload: 1, pcload: 1, next: 142 },
    [Instr.rori]: { imload: 1, pcload: 1, next: 143 },
    [128]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.ADD,
        op2sel: Op2.IMMED,
        next: 0,
    },
    [129]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.SUB,
        op2sel: Op2.IMMED,
        next: 0,
    },
    [130]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.MUL,
        op2sel: Op2.IMMED,
        next: 0,
    },
    [131]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.DIV,
        op2sel: Op2.IMMED,
        next: 0,
    },
    [132]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.MOD,
        op2sel: Op2.IMMED,
        next: 0,
    },
    [133]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.AND,
        op2sel: Op2.IMMED,
        next: 0,
    },
    [134]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.OR,
        op2sel: Op2.IMMED,
        next: 0,
    },
    [135]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.XOR,
        op2sel: Op2.IMMED,
        next: 0,
    },
    [136]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.NAND,
        op2sel: Op2.IMMED,
        next: 0,
    },
    [137]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.NOR,
        op2sel: Op2.IMMED,
        next: 0,
    },
    [138]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.NOT,
        op2sel: Op2.IMMED,
        next: 0,
    },
    [139]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.LSL,
        op2sel: Op2.IMMED,
        next: 0,
    },
    [140]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.LSR,
        op2sel: Op2.IMMED,
        next: 0,
    },
    [141]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.ASR,
        op2sel: Op2.IMMED,
        next: 0,
    },
    [142]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.ROL,
        op2sel: Op2.IMMED,
        next: 0,
    },
    [143]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.ROR,
        op2sel: Op2.IMMED,
        next: 0,
    },

    // non-conditional branches
    [Instr.bar]: { pcload: 1, pcsel: PC.SRC_REG, next: 0 },
    [Instr.bai]: { imload: 1, pcload: 1, next: 144 },
    [144]: { pcload: 1, pcsel: PC.IMMED, next: 0 },
    [Instr.bri]: { imload: 1, pcload: 1, next: BRI_END },
    [BRI_END]: { pcload: 1, pcsel: PC.PLUS_IMMED, next: 0 },

    // comparisons
    [Instr.cmp]: { flags: 1, aluop: ALU.SUB, op2sel: Op2.T_REG, next: 0 },
    [Instr.tst]: { flags: 1, aluop: ALU.AND, op2sel: Op2.T_REG, next: 0 },
    [Instr.cmpi]: { imload: 1, pcload: 1, next: 146 },
    [Instr.tsti]: { imload: 1, pcload: 1, next: 147 },
    [146]: {
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.SUB,
        op2sel: Op2.IMMED,
        next: 0,
    },
    [147]: {
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.AND,
        op2sel: Op2.IMMED,
        next: 0,
    },

    // call(s)
    [Instr.call]: {
        dwrite: 1,
        regsrc: RSrc.PC,
        pcload: 1,
        pcsel: PC.SRC_REG,
        next: 0,
    },
    [Instr.calli]: { imload: 1, pcload: 1, next: 148 },
    [148]: { dwrite: 1, regsrc: RSrc.PC, pcload: 1, pcsel: PC.IMMED, next: 0 },

    // loads and stores
    [Instr.lwr]: {
        dwrite: 1,
        regsrc: RSrc.DATA_BUS,
        addrsel: Addr.SRC_REG,
        next: 0,
    },
    [Instr.swr]: {
        datawrite: 1,
        datasel: Data.DST_REG,
        addrsel: Addr.SRC_REG,
        next: 0,
    },
    [Instr.lwi]: { imload: 1, pcload: 1, next: 149 },
    [149]: { dwrite: 1, regsrc: RSrc.DATA_BUS, addrsel: Addr.IMMED, next: 0 },
    [Instr.swi]: { imload: 1, pcload: 1, next: 150 },
    [150]: {
        datawrite: 1,
        datasel: Data.DST_REG,
        addrsel: Addr.IMMED,
        next: 0,
    },
    [Instr.lwrr]: {
        dwrite: 1,
        regsrc: RSrc.DATA_BUS,
        addrsel: Addr.ALU,
        aluop: ALU.ADD,
        op2sel: Op2.T_REG,
        next: 0,
    },
    [Instr.swrr]: {
        datawrite: 1,
        datasel: Data.DST_REG,
        addrsel: Addr.ALU,
        aluop: ALU.ADD,
        op2sel: Op2.T_REG,
        next: 0,
    },
    [Instr.lwri]: { imload: 1, pcload: 1, next: 151 },
    [151]: {
        dwrite: 1,
        regsrc: RSrc.DATA_BUS,
        addrsel: Addr.ALU,
        aluop: ALU.ADD,
        op2sel: Op2.IMMED,
        next: 0,
    },
    [Instr.swri]: { imload: 1, pcload: 1, next: 152 },
    [152]: {
        datawrite: 1,
        datasel: Data.DST_REG,
        addrsel: Addr.ALU,
        aluop: ALU.ADD,
        op2sel: Op2.IMMED,
        next: 0,
    },

    // stack oriented-intstructions
    [Instr.lwrti]: {
        dwrite: 1,
        regsrc: RSrc.DATA_BUS,
        addrsel: Addr.SRC_REG,
        next: 153,
    },
    [153]: {
        swrite: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.ADD,
        op2sel: Op2.ONE,
        next: 0,
    },
    [Instr.swrdb]: {
        swrite: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.SUB,
        op2sel: Op2.ONE,
        next: Instr.swr,
    },

    // conditional branches
    [Instr.brieq]: { imload: 1, pcload: 1, next: 154 },
    [154]: { cond: Cond.Z, t: BRI_END, f: 0 },
    [Instr.brine]: { imload: 1, pcload: 1, next: 155 },
    [155]: { cond: Cond.Z, f: BRI_END, t: 0 },
    [Instr.brimi]: { imload: 1, pcload: 1, next: 156 },
    [156]: { cond: Cond.N, t: BRI_END, f: 0 },
    [Instr.bripl]: { imload: 1, pcload: 1, next: 157 },
    [157]: { cond: Cond.N, f: BRI_END, t: 0 },
    [Instr.brihs]: { imload: 1, pcload: 1, next: 158 },
    [158]: { cond: Cond.C, t: BRI_END, f: 0 },
    [Instr.brilo]: { imload: 1, pcload: 1, next: 159 },
    [159]: { cond: Cond.C, f: BRI_END, t: 0 },
    [Instr.brihi]: { imload: 1, pcload: 1, next: 160 },
    [160]: { cond: Cond.C, t: 161, f: 0 },
    [161]: { cond: Cond.Z, t: 0, f: BRI_END },
    [Instr.brils]: { imload: 1, pcload: 1, next: 162 },
    [162]: { cond: Cond.C, t: 163, f: BRI_END },
    [163]: { cond: Cond.Z, t: BRI_END, f: 0 },

    //inc and dec
    [Instr.inc]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.ADD,
        op2sel: Op2.ONE,
        next: 0,
    },
    [Instr.dec]: {
        dwrite: 1,
        flags: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.SUB,
        op2sel: Op2.ONE,
        next: 0,
    },

    [Instr.umn]: { flags: 1, aluop: ALU.SUB, op2sel: Op2.T_REG, next: 164 },
    [Instr.umx]: { flags: 1, aluop: ALU.SUB, op2sel: Op2.T_REG, next: 165 },
    [164]: { cond: Cond.C, t: 166, f: 167 },
    [165]: { cond: Cond.C, t: 167, f: 166 },
    [166]: { dwrite: 1, regsrc: RSrc.SRC_REG, next: 0 },
    [167]: { dwrite: 1, regsrc: RSrc.T_REG, next: 0 },

    //push/pop dual
    [Instr.lwrti2]: {
        dwrite: 1,
        regsrc: RSrc.DATA_BUS,
        addrsel: Addr.SRC_REG,
        next: 168,
    },
    [168]: {
        swrite: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.ADD,
        op2sel: Op2.ONE,
        next: 169,
    },
    [169]: {
        twrite: 1,
        regsrc: RSrc.DATA_BUS,
        addrsel: Addr.SRC_REG,
        next: 170,
    },
    [170]: {
        swrite: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.ADD,
        op2sel: Op2.ONE,
        next: 0,
    },

    [Instr.swrdb2]: {
        swrite: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.SUB,
        op2sel: Op2.ONE,
        next: 171,
    },
    [171]: {
        datawrite: 1,
        datasel: Data.T_REG,
        addrsel: Addr.SRC_REG,
        next: 172,
    },
    [172]: {
        swrite: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.SUB,
        op2sel: Op2.ONE,
        next: 173,
    },
    [173]: {
        datawrite: 1,
        datasel: Data.DST_REG,
        addrsel: Addr.SRC_REG,
        next: 0,
    },

    // pop PC
    [Instr.bsp]: { imload: 1, addrsel: Addr.SRC_REG, next: 174 },
    [174]: {
        swrite: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.ADD,
        op2sel: Op2.ONE,
        next: 175,
    },
    [175]: { pcload: 1, pcsel: PC.IMMED, next: 0 },

    // Add/sub w carry
    [Instr.addc]: {
        dwrite: 1,
        flags: 1,
        carry: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.ADD,
        op2sel: Op2.T_REG,
        next: 0,
    },
    [Instr.subc]: {
        dwrite: 1,
        flags: 1,
        carry: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.SUB,
        op2sel: Op2.T_REG,
        next: 0,
    },
    [Instr.addco]: {
        dwrite: 1,
        flags: 1,
        carry: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.ADD,
        op2sel: Op2.ZERO,
        next: 0,
    },
    [Instr.subco]: {
        dwrite: 1,
        flags: 1,
        carry: 1,
        regsrc: RSrc.ALU,
        aluop: ALU.SUB,
        op2sel: Op2.ZERO,
        next: 0,
    },
};

const r = build(UCODE);

accessSync("./out")
writeFileSync("./out/uc.rom", v3HexWordsPlain(r.control));
writeFileSync("./out/ud.rom", v3HexWordsPlain(r.decision));
writeFileSync(
    "./out/inst.dot",
    dot(UCODE, { ...Instr, [BRI_END]: "bri_end", 0: "loadInstr0", 1: "loadInstr1" })
);
